name: Sync from Obsidian and Deploy
on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Sync from Obsidian Repo
      run: |
        git clone https://${{ secrets.OBSIDIAN_TOKEN }}@github.com/tchan1002/obsidian.git temp-obsidian
        cp "temp-obsidian/Obsidian Vault/100 Days"/*.md entries/
        rm -rf temp-obsidian
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build site
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
